### ISSUE TITLE
Decide on config file format

### ISSUE THREAD

**Issue by atc0005** [atc0005/mysql2sqlite#2]
Leaning towards giving go-yaml/yaml a try.

Prototype format:

```yaml
---
- table: table1
  read: placeholder
  write: placeholder
  index: placeholder

- table: table2
  read: placeholder
  write: placeholder
  index: placeholder
```

If this doesn't pan out, then I can fall back to using the previous TOML format.
